### PR TITLE
[WIP] Generates stubs with Buf

### PR DESCRIPTION
**Pull request by Janaka-Steph**
Will be closed in favor of #139 

Current issue: All files would be generated if we didn't have conflict `Failure: file "src/api-spec/protobuf/gen/js/tdex/v1/swap_pb.d.ts" was generated multiple times: once by plugin "buf.build/grpc/plugins/web" and again by plugin "ts-node"`

### CODE REVIEW

**Comment by Janaka-Steph** [comment]
Unfortunately, the JavaScript generator of protoc can only output plain JS, and none of the "official" plugins for gRPC can generate TypeScript (or TS declaration files). There are a some community plugins, for example Improbable's [ts-protoc-gen](https://github.com/improbable-eng/ts-protoc-gen), and [grpc_tools_node_protoc_ts](https://github.com/agreatfool/grpc_tools_node_protoc_ts). You can find some examples in [this repository](https://github.com/badsyntax/grpc-js-typescript).

**Comment by Janaka-Steph** [comment]
Using local protoc plugins: https://github.com/altafan/tdex-sdk/tree/buf
Unfortunately, `grpc-tools` is not supported on Mac M1.

**Comment by altafan** [comment]
We should wait for [#65](https://github.com/tdex-network/tdex-protobuf/pull/65) to be merged before this.

**Review by altafan — CHANGES_REQUESTED** [review]
Besides the cosmetic changes, if I checkout this branch, I'm not able to install the dependencies with following error:
```
$ yarn install

### Logs ###

yarn install v1.22.11
$ yarn buf-generate
yarn run v1.22.11
$ buf generate buf.build/tdex-network/tdex-protobuf
Failure: plugin ts-node: exec: "./node_modules/.bin/protoc-gen-ts": stat ./node_modules/.bin/protoc-gen-ts: no such file or directory
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I suppose the new `preinstall` script in package.json is the cause of this. I would just remove it.

**Comment by altafan** [comment]
@Janaka-Steph I had to remove both `prepare` and `presintall` scripts from package.json to install the dependencies with `yarn install` without errors. Can you try the same?

**Comment by Janaka-Steph** [comment]
> @Janaka-Steph I had to remove both `prepare` and `presintall` scripts from package.json to install the dependencies with `yarn install` without errors. Can you try the same?

I added the preinstall script. With current pr we have local protoc plugins so I would use postinstall instead

**Pull request closed without merging**
